01-ObserverMvc/src/Cooperchip.Observer.Mvc/Models/ErrorViewModel.cs
namespace Cooperchip.Observer.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

01-ObserverMvc/src/Cooperchip.Observer.Mvc/Models/PedidoViewModel.cs
using System;

namespace Cooperchip.Observer.Mvc.Models
{
    public class PedidoViewModel
    {
        public Guid Id { get; set; }
        public string Numero { get; set; }
        public DateTime Data { get; set; }
        public decimal Valor { get; set; }
        public StatusDoPedido Status { get; set; }
    }

    public enum StatusDoPedido
    {
        PedidoPendente = 1,
        AguardandoProcessamento,
        Processando,
        Enviado,
        Entregue,
        Cancelado,
        Recusado,
        Falha,
        Completo
    }

}

01-ObserverMvc/src/Cooperchip.Observer.Mvc/Controllers/HomeController.cs
using Cooperchip.Observer.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Cooperchip.Observer.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Home Acessada!");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

}

01-ObserverMvc/src/Cooperchip.Observer.Mvc/Controllers/PedidoController.cs
using Cooperchip.Observer.Mvc.Configurations.Observer.Interfaces;
using Cooperchip.Observer.Mvc.Configurations.Observer.Services;
using Cooperchip.Observer.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;

namespace Cooperchip.Observer.Mvc.Controllers
{
    public class PedidoController : Controller
    {
        private readonly ILogger _logger;
        private readonly IPedidoService _pedidoService;

        public PedidoController(ILogger<PedidoController> logger, IPedidoService pedidoService)
        {
            _logger = logger;
            _pedidoService = pedidoService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            PedidoViewModel viewModel = new()
            {
                Id = Guid.NewGuid(),
                Numero = "P-2023/764",
                Data = DateTime.Now,
                Valor = 213.90M,
                Status = StatusDoPedido.PedidoPendente
            };
            return View(await Task.FromResult(viewModel));
        }

        [HttpPost]
        public async Task<IActionResult> Index(PedidoViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            Console.WriteLine("");
            //Console.WriteLine("\tADICIONANDO OBSERVADORES");
            _logger.LogInformation("\tADICIONANDO OBSERVADORES:");
            Console.WriteLine("");

            await _pedidoService.Attach(new EmailObserver());
            await _pedidoService.Attach(new SMSObserver());
            await _pedidoService.Attach(new WhatsAppObserver());

            Console.WriteLine("\tATUALIZANDO STATUS DO PEDIDO:");
            Console.WriteLine("");
            //await _pedidoService.Dettach(new WhatsAppObserver());
            //Console.WriteLine("");
            //Console.WriteLine("\tREMOVENDO UM OBSERVADOR");


            await _pedidoService.AtualizaPedido(model);

            return View(model);
        }

    }
}

01-ObserverMvc/src/Cooperchip.Observer.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h2 class="display-4">Benvindos!</h2>
    <p>Leia aqui <a href="https://docs.microsoft.com/aspnet/core">como construir Web Apps com ASP.NET Core</a>.</p>
</div>

<hr />

<div class="container">
    <div class="row">
        <h3><i class="fa fa-list-check"></i>&nbsp;&nbsp;Lista de Pedidos</h3>
    </div>
    <div>
        <table class="table table-striped table-hover minhatabela">
            <thead>
                <tr>
                    <th>Pedido</th>
                    <th>Cliente</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>M-2023/023</td>
                    <td>Carlos A Santos</td>
                    <td>R$ 123,90</td>
                </tr>
                <tr>
                    <td>K-2023/903</td>
                    <td>Maria do Carmo</td>
                    <td>R$ 401,99</td>
                </tr>
                <tr>
                    <td>F-2023/689</td>
                    <td>Eliane Adwigem</td>
                    <td>R$ 203,00</td>
                </tr>

            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function(){
            $('.minhatabela').DataTable();
        });
    </script>
}

01-ObserverMvc/src/Cooperchip.Observer.Mvc/Views/Pedido/Index.cshtml
@model PedidoViewModel
@{
    ViewData["Title"] = "Atualizar Pedido";
    IList<SelectListItem> status = Enum.GetValues(typeof(StatusDoPedido)).Cast<StatusDoPedido>()
    .Select(x => new SelectListItem()
            {
                Text = x.ToString(),
                Value = ((int)x).ToString()
            }).ToList();
}

<div class="container mt-5">
    <div class="row">

        <h2>Acompanhamento de Pedidos</h2>
        <hr />
        <br />

        <div class="col-md-4">

            <form asp-controller="Pedido" asp-action="Index" method="post">
                <div class="form-group mb-2">
                    <label asp-for="Numero" class="control-label"></label>
                    <input asp-for="Numero" class="form-control" readonly="readonly" />
                </div>
                <div class="form-group mb-2">
                    <label asp-for="Data" class="control-label"></label>
                    <input asp-for="Data" class="form-control" readonly="readonly" />
                </div>
                <div class="form-group mb-2">
                    <label asp-for="Valor" class="control-label"></label>
                    <input asp-for="Valor" class="form-control" readonly="readonly" />
                </div>
                <div class="form-group mb-2">
                    <label asp-for="Status" class="control-label"></label>
                    <select asp-for="Status" asp-items="status" class="form-control"></select>
                </div>
                <div class="form-group mb-3">
                    <input type="submit" value="Atualizar" class="btn btn-outline-success" />
                </div>
            </form>
        </div>
    </div>
</div>

01-ObserverMvc/src/Cooperchip.Observer.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cooperchip | Observer MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cooperchip.Observer.Mvc.styles.css" asp-append-version="true" />

    <link href="~/fontawesome/css/all.min.css" rel="stylesheet" />
    <link href="~/fontawesome/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/datatables-1.13.3/css/jquery.datatables.min.css" rel="stylesheet" />
    <link href="~/datatables-1.13.3/css/datatables.datatables.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home"></i>&nbsp;&nbsp;Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedido" asp-action="Index">Pedido</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2007 / @DateTime.Now.Year - Cooperchip, Inc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Política de Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/datatables-1.13.3/js/jquery.datatables.min.js"></script>
    <script src="~/datatables-1.13.3/js/datatables.datatables.min.js"></script>
    <script src="~/fontawesome/js/all.min.js"></script>
    <script src="~/fontawesome/js/fontawesome.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>